# -*- coding: utf-8 -*-
"""14_Basics_of_prompt_engineering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Sa-_KpV0MQbKLD3ppNutjDThqoGMa5je

# Basics of Prompt Engineering

*Robert Barcik (robert@barcik.training)*

## **What is Prompt Engineering?**

### **Introduction to Prompt Engineering**

Prompt engineering refers to the careful design and structuring of input prompts that are given to AI language models to produce desired outputs. These prompts guide the AI's responses, helping to shape them in a way that meets specific needs. When interacting with language models, the way a question or command is phrased can significantly influence the quality and relevance of the response.

In essence, prompt engineering is about crafting the "questions" we ask the AI to get the "answers" we need. This practice is fundamental in ensuring that the AI understands the context and purpose of the interaction, resulting in accurate, coherent, and useful outputs.

### **Why is Prompt Engineering Important?**

Prompt engineering is crucial for several reasons. First, it allows us to control the quality of the AI's responses. By carefully crafting prompts, we can guide the AI to provide more precise, relevant, and contextually appropriate answers. This control is vital, especially in scenarios where the output must meet high standards of accuracy or clarity, such as customer support, content creation, or technical documentation.

Second, prompt engineering helps unlock the full capabilities of language models. AI models are inherently flexible and can handle various tasks, but they need clear instructions to perform effectively. Good prompt design clarifies these instructions, ensuring that the AI knows what to do and how to do it.

Finally, effective prompt engineering reduces ambiguity. Ambiguous or vague prompts can lead to off-topic or nonsensical answers. By being clear and specific in our prompts, we minimize the chances of misinterpretation and improve the reliability of the AI's responses.

### **The Role of an Architect in Prompt Engineering**

While prompt engineering focuses on crafting effective inputs for AI models, it must be combined with strategic thinking and architectural design to solve real-world problems effectively. In other words, it's not just about what you send to the model but also about how this fits into the broader system.

An "architect" in this context refers to someone who understands how to structure the interaction between the user, the AI, and the surrounding environment in a seamless and efficient manner. This involves:

1. **Breaking Down Problems:** Before designing prompts, it's essential to decompose the problem into manageable parts. This step ensures that each aspect of the task is understood and addressed correctly. For instance, if you're developing a customer support chatbot, you would break down tasks into greeting the user, understanding the query, fetching information, and providing a response.

2. **Integrating Prompts with Python Code:** Effective prompt engineering requires embedding the prompts within a functional Python framework. This means creating functions that handle the generation of prompts, processing user inputs, and managing the AI's responses. It also involves setting up error handling, logging, and data management to ensure that the application runs smoothly.

3. **Maintaining a Feedback Loop:** Prompt engineering is often iterative. As you interact with the AI, you will learn which prompts work best and which need adjustment. This requires building a feedback loop within your application to monitor and refine prompts based on user interactions and outcomes.

# 1. Writting clear instructions

## 1.1 Tactic: Add specific details for better responses

When you want a relevant and accurate response, ensure your requests include essential details and context. If you don't, the model might interpret your query incorrectly.

Here are some examples to illustrate how adding specific details to your queries can improve the relevance and quality of the responses:

| Vague                                   | Detailed                                                                                     |
|-----------------------------------------|----------------------------------------------------------------------------------------------|
| How do I cook pasta?                    | How do I cook al dente spaghetti for a carbonara dish?                                       |
| Write a function to sort a list.        | Write a Python function to sort a list of dictionaries by a specific key. Include comments to explain the logic. |
| Describe the history of the internet.   | Provide a brief history of the internet, highlighting key milestones from the 1960s to the present. |

Let's import libraries:
"""

# Assuming OPENAI_API_KEY is set as an environment variable
from openai import OpenAI
import os
import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning)
#!pip install opencv-python matplotlib
api_key = os.getenv("OPENAI_API_KEY")
client = OpenAI(api_key=api_key)

"""First, we'll examine a vague request to the OpenAI API:"""

# Request to OpenAI API without clear instructions
response = client.chat.completions.create(
    model="gpt-3.5-turbo",
    messages=[
        {"role": "user", "content": "Tell me about blockchain technology."}
    ],
    max_tokens=200
)

# Printing the response
print(response.choices[0].message.content)

"""Now, we'll look at a request to the OpenAI API with clear instructions and specific details."""

# Request to OpenAI API with clear instructions
response = client.chat.completions.create(
    model="gpt-3.5-turbo",
    messages=[
        {"role": "user", "content":
         "Explain in short how blockchain technology works and provide one application in \
          finance, healthcare, and supply chain management."}
    ],
    max_tokens=300
)

# Printing the response
print(response.choices[0].message.content)

"""## 1.2 Tactic: Ask the model to adopt a specific persona

Persona adoption means guiding the AI to respond like **a particular character or role**. This approach has many benefits. Firstly, it makes responses more engaging and relatable by reflecting a specific persona. Secondly, it ensures consistency, improving the coherence and trustworthiness of interactions. Lastly, it allows for tailored responses that better meet the needs and preferences of different audiences.

Examples of persona adoption could be:
- **Educational Tutor**: The model adopts a patient and explanatory style, ideal for teaching complex topics.
- **Customer Service Agent**: The model uses a friendly and helpful tone to assist with customer inquiries.
- **Technical Expert**: The model provides detailed and precise information suitable for professional discussions.

First, we will demonstrate how the AI responds to a question about medical issues without adopting any specific persona. In this case, the AI will objectively provide the causes without any consideration for the user's emotional state:
"""

# Request to OpenAI API without specifying a persona
response = client.chat.completions.create(
    model="gpt-3.5-turbo",
    messages=[
        {"role": "user", "content":
         "I'm feeling very anxious because I've been having headaches and dizziness. What could be causing this?"}
    ],
    max_tokens=150
)

# Printing the response
print(response.choices[0].message.content)

"""When dealing with medical concerns, people often feel anxious and stressed. By adopting an empathetic and caring persona, the AI can respond in a way that not only provides accurate information but also helps to calm and reassure the user. This persona will use a gentle and understanding tone, acknowledge the user's feelings, while offering the information he/she needs.

We will specify this persona for "system" role within parameter "messages":
"""

# Request to OpenAI API with a specific persona
response = client.chat.completions.create(
    model="gpt-3.5-turbo",
    messages=[
        {"role": "system", "content":
         "You are an empathetic and caring assistant who helps to calm down and reassure people seeking medical advice."},

        {"role": "user", "content":
         "I'm feeling very anxious because I've been having headaches and dizziness. What could be causing this?"}
    ],
    max_tokens=150
)

# Printing the response
print(response.choices[0].message.content)

"""## 1.3 Tactic: Separating parts of the input

Another tactic is using delimiters to clearly separate different sections of the input. Delimiters, such as **triple quotation marks**, **section titles** and **XML tags** can help specify which parts of the text should be treated differently making it easier for the AI to understand and process the information. This technique ensures that each section is treated appropriately according to its context, improving the overall quality of the interaction.

For simple tasks like these, using delimiters might not significantly impact the output quality. However, as tasks become more complex, it becomes increasingly important to clarify task details. Ensuring that the model clearly understands what you are asking will prevent confusion and improve the accuracy of its responses.

"""

# Without delimiters

response = client.chat.completions.create(
    model="gpt-3.5-turbo",
    messages=[
        {"role": "user", "content":
        """
        Summarize the arguments presented in each article. Then, evaluate which article presents a stronger argument
        and explain your reasoning. Online learning has revolutionized education by providing students with unprecedented
        access to resources and flexibility. One of the key advantages of online learning is that it allows students
        to learn at their own pace. Unlike traditional classroom settings where students must adhere to a fixed schedule,
        online courses offer the flexibility to review materials, take breaks, and move forward at a comfortable speed.
        This personalized approach can significantly enhance a student’s understanding and retention of the subject matter.
        Additionally, online learning platforms often include a variety of multimedia tools such as videos, interactive quizzes,
        and forums, which cater to different learning styles and make the learning experience more engaging and effective.
        The accessibility of online learning also means that education can be democratized, reaching students who may not
        have had the opportunity to attend traditional schools due to geographical, financial, or personal constraints.
        Despite the growing popularity of online learning, there are several challenges and limitations that cannot be
        overlooked. One significant drawback is the lack of face-to-face interaction, which can affect the learning experience.
        In traditional classroom settings, students benefit from real-time feedback, direct engagement with instructors,
        and collaborative learning with peers. These interactions are difficult to replicate in an online environment,
        which can lead to feelings of isolation and disengagement. Moreover, the effectiveness of online learning heavily
        depends on a student’s self-discipline and motivation. Without the structured environment of a physical classroom,
        students may struggle to stay on track, complete assignments, and maintain consistent study habits. Technical issues
        such as unreliable internet access and the need for updated devices can also hinder the learning process, especially
        for students in underserved areas. Therefore, while online learning offers flexibility and accessibility, it also
        presents challenges that must be addressed to ensure a comprehensive and effective educational experience.
        """}
    ],
    max_tokens=200
)

# Printing the response
print(response.choices[0].message.content)

# With delimiters

response = client.chat.completions.create(
    model="gpt-3.5-turbo",
    messages=[
        {"role": "system", "content":
         "You will be provided with two articles about the same topic, each delimited by XML tags. \
        First, summarize the arguments presented in each article. Then, evaluate which article presents \
        a stronger argument and explain your reasoning."},

        {"role": "user", "content":
        """
        <article>
        Online learning has revolutionized education by providing students with unprecedented access to resources and
        flexibility. One of the key advantages of online learning is that it allows students to learn at their own
        pace. Unlike traditional classroom settings where students must adhere to a fixed schedule, online courses
        offer the flexibility to review materials, take breaks, and move forward at a comfortable speed. This personalized
        approach can significantly enhance a student’s understanding and retention of the subject matter. Additionally,
        online learning platforms often include a variety of multimedia tools such as videos, interactive quizzes, and forums,
        which cater to different learning styles and make the learning experience more engaging and effective. The accessibility
        of online learning also means that education can be democratized, reaching students who may not have had the opportunity
        to attend traditional schools due to geographical, financial, or personal constraints.
        </article>

        <article>
        Despite the growing popularity of online learning, there are several challenges and limitations that cannot
        be overlooked. One significant drawback is the lack of face-to-face interaction, which can affect the learning
        experience. In traditional classroom settings, students benefit from real-time feedback, direct engagement with
        instructors, and collaborative learning with peers. These interactions are difficult to replicate in an online
        environment, which can lead to feelings of isolation and disengagement. Moreover, the effectiveness of online
        learning heavily depends on a student’s self-discipline and motivation. Without the structured environment of a
        physical classroom, students may struggle to stay on track, complete assignments, and maintain consistent study habits.
        Technical issues such as unreliable internet access and the need for updated devices can also hinder the learning process,
        especially for students in underserved areas. Therefore, while online learning offers flexibility and accessibility,
        it also presents challenges that must be addressed to ensure a comprehensive and effective educational experience.
        </article>
        """}
    ],
    max_tokens=350
)

# Printing the response
print(response.choices[0].message.content)

"""## 1.4 Tactic: List the specific steps necessary to complete a task

Some tasks are most effectively outlined as a series of steps. Clearly detailing each step can help the model follow instructions more easily.

This approach is beneficial because:
- it reduces ambiguity,
- ensures that the model understands the sequence of actions required,
- and improves the accuracy and relevance of the responses.

By breaking down complex tasks into simpler, ordered steps, you can enhance the model's performance and reliability.

"""

response = client.chat.completions.create(
    model="gpt-3.5-turbo",
    messages=[
        {"role": "user", "content":
        """
        Summarize this text in one sentence and provide key points. Artificial intelligence
        (AI) has the potential to revolutionize various industries by automating tasks, providing
        insights from big data, and improving decision-making processes. AI technologies, such as
        machine learning, natural language processing, and computer vision, can enhance productivity,
        efficiency, and innovation. However, the widespread adoption of AI also raises ethical and
        societal concerns, including issues of privacy, security, and the potential displacement of
        jobs. To fully harness the benefits of AI, it is crucial to address these challenges through
        thoughtful regulation, interdisciplinary research, and collaboration between stakeholders from
        different sectors. Additionally, continuous learning and adaptation are essential to keep up
        with the rapid advancements in AI and to ensure its responsible and beneficial integration into
        society. As AI continues to evolve, it will play an increasingly significant role in shaping the
        future of work, healthcare, transportation, and many other fields.
        """}
    ],
    max_tokens=300
)

# Printing the response
print(response.choices[0].message.content)

"""Setting system settings with clear instructions on how to process the input led to a more comprehensive, structured, and informative response - the summary provides a concise overview, while the bullet points broke down the main ideas:"""

response = client.chat.completions.create(
    model="gpt-3.5-turbo",
    messages=[
        {"role": "system", "content":
         "Follow these step-by-step instructions to respond to user inputs. "
         "Step 1 - The user will give you text enclosed in triple quotes. "
         "Provide a one-sentence summary of this text, starting with 'Summary: '. "
         "Step 2 - Extract the key points from the summary in bullet points, starting with 'Key Points: '."},

        {"role": "user", "content":
         """
         Artificial intelligence (AI) has the potential to revolutionize various industries by
         automating tasks, providing insights from big data, and improving decision-making processes.
         AI technologies, such as machine learning, natural language processing, and computer vision,
         can enhance productivity, efficiency, and innovation. However, the widespread adoption of AI
         also raises ethical and societal concerns, including issues of privacy, security, and the potential
         displacement of jobs. To fully harness the benefits of AI, it is crucial to address these challenges
         through thoughtful regulation, interdisciplinary research, and collaboration between stakeholders from
         different sectors. Additionally, continuous learning and adaptation are essential to keep up with the
         rapid advancements in AI and to ensure its responsible and beneficial integration into society. As AI
         continues to evolve, it will play an increasingly significant role in shaping the future of work, healthcare,
         transportation, and many other fields.
         """}
    ],
    max_tokens=300
)

# Printing the response
print(response.choices[0].message.content)

"""## 1.5 Tactic: Define the desired output length

You can request the model to generate outputs of a specific target length, such as a certain number of words, **sentences**, **paragraphs**, or **bullet points**. This ensures that the responses are tailored to your exact needs and allows for better control over the level of detail provided. It also improves readability and structure, making the information easier to digest and use.

Note: Asking the model to produce an exact word count may not be highly precise. It is more reliable in generating outputs with a specified number of paragraphs or bullet points.
"""

response = client.chat.completions.create(
    model="gpt-3.5-turbo",
    messages=[
        {"role": "user", "content":
        """
        Summarize the following text:
        Artificial intelligence (AI) is transforming various industries by automating tasks, providing
        insights through data analysis, and enhancing decision-making processes. Machine learning, a
        subset of AI, allows systems to learn and improve from experience without being explicitly
        programmed. This technology is used in numerous applications, including healthcare for predictive
        diagnostics, finance for fraud detection, and transportation for optimizing routes. Despite its benefits,
        AI also raises ethical concerns, such as data privacy, algorithmic bias, and the potential for job displacement.
        Addressing these issues requires careful consideration and the implementation of ethical guidelines to ensure AI's
        responsible use and development.
        """}
    ],
    max_tokens=150
)

# Printing the response
print(response.choices[0].message.content)

response = client.chat.completions.create(
    model="gpt-3.5-turbo",
    messages=[
        {"role": "user", "content":
        """
        Summarize the following text in 2 short bullet points:
        Artificial intelligence (AI) is transforming various industries by automating tasks, providing insights
        through data analysis, and enhancing decision-making processes. Machine learning, a subset of AI, allows
        systems to learn and improve from experience without being explicitly programmed. This technology is used
        in numerous applications, including healthcare for predictive diagnostics, finance for fraud detection,
        and transportation for optimizing routes. Despite its benefits, AI also raises ethical concerns, such as
        data privacy, algorithmic bias, and the potential for job displacement. Addressing these issues requires
        careful consideration and the implementation of ethical guidelines to ensure AI's responsible use and development.
        """}
    ],
    max_tokens=200
)

# Printing the response
print(response.choices[0].message.content)

"""# 2. Providing reference text

## 2.1 Tactic: Guide the model to answer using reference text

We can instruct the model to answer questions based on a provided reference text. By supplying the model with trusted and relevant information, you can direct it to use this information to generate accurate answers.

This approach ensures the reliability and accuracy of the model's responses by grounding them in verified sources. It reduces the likelihood of misinformation and enhances the quality of answers by referencing specific and relevant data.
"""

response = client.chat.completions.create(
    model="gpt-3.5-turbo",
    messages=[
        {"role": "user", "content":
        """
        How many deaths worldwide are attributed to household air pollution?
        """}
    ],
    max_tokens=150
)

# Printing the response
response.choices[0].message.content

response = client.chat.completions.create(
    model="gpt-3.5-turbo",
    messages=[
        {"role": "system", "content":
         "Refer to the provided text enclosed within XML tags to answer the questions. If the answer is not found in the text, \
         respond with 'I could not find an answer.'"},

        {"role": "user", "content":
        """
        <article>
        The keyword co-occurrence network reveals a strong correlation between air pollution and the
        burden of disease. As air pollution intensifies, there is a commensurate rise in the global burden of
        disease. In , the toll of fatalities attributed to air pollution across the globe amounted to 6.67 million.
        Indoor air pollution exhibits a strong correlation with family health. The associated effects and disease
        burden garner escalating attention from academics and governments. Based on the statistical data derived
        from the Global Burden of Disease, household air pollution from solid fuels has caused 2.3 million deaths
        worldwide. Among them, 1.06 million deaths are attributed to cardiovascular diseases, 420,000 deaths
        are caused by respiratory infections and tuberculosis, while 398,000 deaths are associated with chronic
        respiratory diseases. According to the World Health Organization, the utilization of solid fuels and
        incomplete combustion leading to household air pollution will result in 3.2 million premature deaths
        worldwide. Thus, when considering the impact of air pollution on health, indoor space is a crucial
        microenvironment that needs to be given ample attention.
        </article>

        How many deaths worldwide are attributed to household air pollution?
        """}
    ],
    max_tokens=150
)

# Printing the response
print(response.choices[0].message.content)

"""## 2.2 Tactic: Guide the model to answer with citations from reference texts

You can easily instruct the model to include citations in its answers by referencing specific sections from the provided documents. It allows the citations in the output to be programmatically verified through string matching within the given texts.

This approach can significantly improve the trustworthiness of the model's outputs, particularly in academic or professional settings where source validation is crucial.
"""

response = client.chat.completions.create(
    model="gpt-3.5-turbo",
    messages=[
        {
            "role": "system",
            "content":
            """
            You will be given a document delimited by XML tags and a question. Your task is to answer the question using
            only the information from the provided document and to cite the relevant passages. If the document does not
            contain enough information to answer the question, write: 'I could not find an answer.' Any answer provided
            must include a citation. Use the following format to cite relevant passages: ({"citation": …})
            """
        },
        {
            "role": "user",
            "content":
            """
            <article>
            The keyword co-occurrence network reveals a strong correlation between air pollution and the burden of disease.
            As air pollution intensifies, there is a commensurate rise in the global burden of disease. In , the toll of
            fatalities attributed to air pollution across the globe amounted to 6.67 million. Indoor air pollution exhibits
            a strong correlation with family health. The associated effects and disease burden garner escalating attention
            from academics and governments. Based on the statistical data derived from the Global Burden of Disease, household
            air pollution from solid fuels has caused 2.3 million deaths worldwide. Among them, 1.06 million deaths are
            attributed to cardiovascular diseases, 420,000 deaths are caused by respiratory infections and tuberculosis,
            while 398,000 deaths are associated with chronic respiratory diseases. According to the World Health Organization,
            the utilization of solid fuels and incomplete combustion leading to household air pollution will result in 3.2 million
            premature deaths worldwide. Thus, when considering the impact of air pollution on health, indoor space is a crucial
            microenvironment that needs to be given ample attention.
            </article>

            How many deaths worldwide are attributed to household air pollution?
            """
        }
    ],
    max_tokens=150
)

# Printing the response
print(response.choices[0].message.content)

"""# Few-shot prompting

Few-shot prompting is a technique where you provide the AI model with a small number of examples demonstrating the task you want it to perform. By showing these examples, or "shots," you give the model context and a pattern to follow.

If we use zero-shot prompting, we simply ask the model to classify a statement's sentiment:
"""

# Request to OpenAI API (zero-shot prompting)
response = client.chat.completions.create(
    model="gpt-4o-mini",
    messages=[
        {"role": "user", "content": "Classify the following Gen-Z style statement as Positive, Negative, or Neutral: \
        'This party is mid fr fr no cap.'"}
    ],
    max_tokens=100
)

# Printing the response
print(response.choices[0].message.content)

"""In contrast, with few-shot prompting, we provide examples of Gen-Z statements with their corresponding sentiments. The model can better understand how to evaluate similar statements, potentially leading to more accurate classifications."""

# Request to OpenAI API (few-shot prompting)
response = client.chat.completions.create(
    model="gpt-4o-mini",
    messages=[
        {
            "role": "system",
            "content": "You are an AI trained to classify Gen-Z style statements as Positive, Negative, or Neutral."
        },
        {
            "role": "user",
            "content": """Here are some examples:
            1. Statement: 'That fit is fire, you slayed'
               Sentiment: Positive
            2. Statement: 'I'm lowkey stressed about this exam'
               Sentiment: Negative
            3. Statement: 'This new album straight bussin, no cap'
               Sentiment: Positive

            Now, classify the following statement:
            Statement: 'It's giving boring vibes ngl'

            """
        }
    ],
    max_tokens=50
)

# Printing the response
print(response.choices[0].message.content)

"""# Chain-of-Thought Prompting

Chain-of-thought prompting is a technique that directs a model through a structured reasoning process to address complex problems. Rather than generating an answer in one step, this method decomposes the problem into sequential, logical components, guiding the model through each step systematically.

This technique is beneficial in scenarios that involve multi-step reasoning or complex problem-solving, such as math problems, logical puzzles, or tasks requiring detailed explanations.
"""

# Chain-of-thought prompt
response = client.chat.completions.create(
    model="gpt-3.5-turbo",
    messages=[
        {"role": "user", "content":
            """
            Question: A train travels 90 kilometers in 2 hours. How long will it take to travel 225 kilometers at the same speed?"
            Answer:
            Let's break this down step by step:
            1. First, we need to calculate the speed of the train. To do that, we divide the distance traveled by the time taken.
               So, the speed of the train is 90 kilometers divided by 2 hours, which equals 45 kilometers per hour.
            2. Now, we know the speed of the train is 45 kilometers per hour. Next, we calculate how long it will take to travel 225 kilometers.
            3. To do that, we divide 225 kilometers by the speed of 45 kilometers per hour.
            4. 225 kilometers divided by 45 kilometers per hour equals 5 hours.

           So the answer is 5 hours.

           Question: A car travels 150 kilometers using 12 liters of fuel. If the car needs to travel 450 kilometers, how much fuel will it require?
           Assume the fuel efficiency remains constant."
            """}
    ],
    max_tokens=500
)

# Printing the response
print(response.choices[0].message.content)

"""# Self-Ask Prompting

We can imagine self-ask prompting as an internal dialogue or a structured brainstorming session. The model essentially "talks to itself," asking and answering questions to build up to a final, comprehensive answer. This process mimics how a human expert might approach a complex problem, breaking it down into manageable pieces, addressing each in turn, and then synthesizing the information into a cohesive response.

This can be particularly beneficial in several scenarios:
- dealing with complex, multi-faceted questions that require breaking down into smaller, more manageable parts
- for tasks that benefit from a step-by-step analysis or problem-solving approach
- when transparency in the reasoning process is important
- in situations where the initial question might be too broad or vague
"""

# Self-ask prompt
response = client.chat.completions.create(
    model="gpt-4o-mini",
    messages=[

        {"role": "user", "content": """
Question: How could the implementation of a universal basic income affect wealth inequality, job markets, and economic growth in a developed country?
Are follow up questions needed here: Yes.
Follow up: How might universal basic income impact wealth inequality?
Intermediate answer: Universal basic income could potentially reduce wealth inequality by providing a financial safety net for all citizens, ensuring a minimum standard of living.
Follow up: What effect could universal basic income have on job markets?
Intermediate answer: It might reduce the pressure to work in low-wage jobs, potentially leading to increased bargaining power for workers and changes in the labor market structure.
Follow up: How could universal basic income influence economic growth?
Intermediate answer: Universal basic income could stimulate consumer spending and potentially boost economic growth, but it may also lead to inflation or reduced productivity if not implemented carefully.
So the final answer is: The implementation of a universal basic income in a developed country could potentially reduce wealth inequality by providing a financial safety net, alter job markets by changing worker dynamics, and affect economic growth through increased consumer spending, though careful implementation would be crucial to manage potential negative effects like inflation.

Question: How might the widespread adoption of autonomous vehicles impact urban planning and infrastructure in major cities over the next 20 years?
Are follow up questions needed here:

"""}
    ],
    max_tokens=1000
)

# Printing the response
print(response.choices[0].message.content)